experiment:
  output_root: "./outputs"
  seed: 42

data:
  subjects:
    - name: "sub4"
      enabled: True
      input_stacks: 
        - /nfs/home/kmuhammad/data/real_cases/simpleData/sub4/2D/T2W/T2WtraBHSENSEs2901a1029.nii.gz 
        - /nfs/home/kmuhammad/data/real_cases/simpleData/sub4/2D/T2W/T2WCorBHSENSEs2801a1028.nii.gz 
        - /nfs/home/kmuhammad/data/real_cases/simpleData/sub4/2D/T2W/T2WsagBHSENSEs3001a1030.nii.gz 
      input_masks:  
        - /nfs/home/kmuhammad/data/real_cases/simpleData/sub4/2D/T2W/T2WtraBHSENSEs2901a1029_mask.nii.gz 
        - /nfs/home/kmuhammad/data/real_cases/simpleData/sub4/2D/T2W/T2WCorBHSENSEs2801a1028_mask.nii.gz 
        - /nfs/home/kmuhammad/data/real_cases/simpleData/sub4/2D/T2W/T2WsagBHSENSEs3001a1030_mask.nii.gz  

reconstruction:
  spacing: [1, 1, 1]
  psf_scale_factor: 1.0
  slice_thickness: [5, 5, 5]

model:
  num_gaussians: 100000
  init_type: "content_adaptive" 
  init_lambda: 0.0 # 0.0 = only edges, 1.0 = uniform. 0.2 avoids holes in flat tissue.

flags:
  use_motion_correction: True
  use_slice_scaling: True
  use_slice_uncertainty: True # Enables Aleatoric Loss
  use_psf: True
  use_masks: True

training:
  max_epochs: 500
  batch_size: 10000000 # All points per batch (pseudobatch), actual batching not implemented yet
  neighbors: 50
  top_k_every: 80
  
  learning_rates:
    position: 3.75e-2 
    scaling: 2.5e-2
    rotation: 1.0e-2
    color: 1.0e-2
    motion_rot: 2.5e-4
    motion_trans: 1.0e-2
    slice_scale: 1.0e-2
    slice_weight: 1.0e-2

  loss_weights:
    lambda_l2_scale: 0.0025 #1 #0.0025
    log_scale_target: 0.5

preprocessing:
  bias_field_correction: False
  denoise: False
  dilate_mask_sigma: 0.5
